Install Stepup SAML bundle
OpenConext-Attic/Stepup-ReadID pull request #4
Opened 2020-02-26 14:43 UTC by MKodde

The installation includes the configuration of the bundle for IdP use.

For now some todo's remain:
1. Do not use the default cert+private key from the SAML bundle
2. Move configuration parameters to a more easily overwritable
paramteres.yaml file
3. Provide some test coverage

2020-03-24 09:36 UTC, sgomez commented on config/packages/framework.yaml
> +    templating:
This is deprecated: [UPGRADE 4.3](https://github.com/symfony/symfony/blob/master/UPGRADE-4.3.md#frameworkbundle)

2020-03-24 09:36 UTC, sgomez commented on config/packages/surfnet_saml.yml
> +parameters:
How this is only to development environments. Maybe the best location is inside `config/packages/dev` directory.

2020-03-24 09:50 UTC, MKodde commented on config/packages/framework.yaml
> +    templating:
I know, but the stepup saml bundle still requires this as a feature. It's on the agenda to address this, but will have to be fixed in the bundle.

2020-03-24 09:55 UTC, MKodde commented on config/packages/surfnet_saml.yml
> +parameters:
Yes, good point. No need to have those test params in that global config file.

2020-03-25 07:18 UTC, sgomez commented on config/packages/framework.yaml
> +    templating:
Fortunately we have used symfony 4.4. :-)

2020-03-25 08:31 UTC, sgomez approved these changes

2020-03-25 10:06 UTC, sgomez requested changes
I realized that you are using deptrac, so Controller must be located in the Infrastructure folder

2020-03-25 13:02 UTC, sgomez approved these changes

2020-03-25 13:15 UTC, merged